# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('rfid', ['core', 'network', 'mobility','applications', 'propagation'])
    module.source = [
        'model/rfid.cc',
        'model/rfid-channel.cc',
        'model/rfid-phy.cc',
        'model/rfid-phy-state.cc',
        'model/rfid-tag-identification.cc',
        'model/rfid-reader-identification.cc',
        'model/rfid-identification.cc',
        'model/rfid-net-device.cc',
        'model/epc-header.cc',
        'model/epc-memory.cc',
        'model/rfid-configuration.cc',
        'helper/rfid-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('rfid')
    module_test.source = [
        'test/rfid-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'rfid'
    headers.source = [
        'model/rfid.h',
        'model/rfid-channel.h',
        'model/rfid-phy.h',
        'model/rfid-phy-state.h',
        'model/rfid-tag-identification.h',
        'model/rfid-reader-identification.h',
        'model/rfid-identification.h',
        'model/rfid-net-device.h',
        'model/epc-header.h',
        'model/epc-memory.h',
        'model/rfid-configuration.h',
        'model/rfid-preamble.h',
        'helper/rfid-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

